version: "3.9"
services:
  frontend:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
  backend:
    build: ./server
    ports:
      - "5000:5000"
